server:
  port: 30000

#阿里云对象存储
spring:
  cloud:
    alicloud:
#      阿里云主账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM账号进行API访问或日常运维，请登录RAM控制台创建RAM账号。
      access-key:
      secret-key:
      bucket: mall2021
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
